import {
  Entity,
  PrimaryColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm';

/**
 * TypeORM entity representing a refresh token in the database.
 * Maps to the 'refresh_tokens' table and stores JWT refresh tokens
 * for user authentication session management.
 */
@Entity('refresh_tokens')
export class RefreshTokenOrmEntity {
  /** Unique identifier for the refresh token record (UUID format) */
  @PrimaryColumn('uuid')
  id: string;

  /** The JWT refresh token string. Indexed and unique for fast lookups */
  @Column({ unique: true })
  @Index()
  token: string;

  /** Foreign key reference to the user who owns this token. Indexed for efficient queries */
  @Column({ name: 'user_id' })
  @Index()
  userId: string;

  /** Timestamp when the refresh token expires and becomes invalid */
  @Column({ name: 'expires_at' })
  expiresAt: Date;

  /** Flag indicating whether the token has been manually revoked. Defaults to false */
  @Column({ name: 'is_revoked', default: false })
  isRevoked: boolean;

  /** Timestamp when the token record was created. Auto-generated by TypeORM */
  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  /** Timestamp when the token record was last updated. Auto-managed by TypeORM */
  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}
