export const INJECTION_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  TOKEN_REPOSITORY: 'TOKEN_REPOSITORY',
  LOGGER: 'LOGGER',
  HTTP_CLIENT: 'HTTP_CLIENT',
  EMAIL: 'EMAIL',
  CACHE: 'CACHE',
  STRAPI_MODULE_REPOSITORY: 'STRAPI_MODULE_REPOSITORY',
} as const;
